### ISSUE TITLE
Tampa Bay Data Engineering Group - Events

### ISSUE THREAD

**Issue by joeblankenship1** [TampaDevs/events.api.tampa.dev#3]
I would like to add the TBDEG meetup events to the API. Please let me know if there are any submission criteria or actions required from me to validate and implement this. Thanks!
URL: https://www.meetup.com/tampa-bay-data-engineering-group/

**Comment by chtzvt** [comment]
Hey @joeblankenship1!

I can confirm that TBDEG event data is being returned from the API:

<img width="965" alt="image" src="https://github.com/TampaDevs/events.api.tampa.dev/assets/7227500/bdb0cc68-593b-4a47-828b-001045a6b73f">
