### ISSUE TITLE
Tech Success Network - Add to Calendar

### ISSUE THREAD

**Issue by suzannericci** [TampaDevs/events.api.tampa.dev#45]
I'd like to request that my group be added to the Events API.

Meetup group name: Tech Success Network
Meetup group URL: https://www.meetup.com/techsuccessnetwork/

Meetup group description: The Tech Success Network connects like-minded individuals who are looking to grow their careers and stay ahead of the curve in the ever-evolving world of technology. From career strategy resources to networking opportunities to knowledge sharing, the Tech Success Network provides a supportive environment where you can thrive and achieve your goals. Whether you're a seasoned pro or a newcomer, join us and take your tech career to new heights!

If your group has a homepage separate from meetup.com, please provide the URL:

**Comment by chtzvt** [comment]
Hey @suzannericci,

Thanks for opening an issue- I've added Tech Success Network to the Events API.

You can now use features like:

- Your own embeddable next widget at https://events.api.tampa.dev/widget/next-event?groups=techsuccessnetwork, which is great to include on web pages (see the [Tampa Devs homepage](https://tampadevs.com) for a live example). 
- Your own public events RSS feed at https://events.api.tampa.dev/rss?groups=techsuccessnetwork. 
- Inclusion on the public [tampa.dev events carousel](https://tampa.dev)
- Inclusion on the public [tampa.dev upcoming events page](https://tampa.dev/upcoming-events)

As well as every other feature of the API (JSON, filters, syndicated Slack summaries, and so on).

Your group's iCal feed is https://events.api.tampa.dev/ical?groups=techsuccessnetwork. The master feed is periodically refreshed by Google Calendar once per day, so you should see your events appear on the [Public Events Calendar](https://go.tampa.dev/calendar) within the next 24-48 hours. The API data feed is refreshed every 30 minutes for all groups.

I have also done the same for your Tampa Cybersecurity Training group-- simply replace `techsuccessnetwork` in the above URLs with `tampa-cybersecurity-training` for the individual equivalents, or specify them both (`groups=techsuccessnetwork,tampa-cybersecurity-training`) to use features like an embeddable [combined next event carousel](https://events.api.tampa.dev/widget/carousel?groups=techsuccessnetwork,tampa-cybersecurity-training), [combined RSS feed](https://events.api.tampa.dev/rss?groups=techsuccessnetwork,tampa-cybersecurity-training), or [combined iCal feed](https://events.api.tampa.dev/ical?groups=techsuccessnetwork,tampa-cybersecurity-training)).

Thank you, and feel free to reopen this issue if you have any questions or other needs!
