### ISSUE TITLE
Tampa M365 - Social @ Magnanimous

### ISSUE THREAD

**Issue by ITAndy23** [TampaDevs/events.api.tampa.dev#70]
https://www.meetup.com/tampa-m365/events/302992515/?eventOrigin=group_upcoming_events

Join us for an awesome social gathering at Magnanimous in Seminole Heights on Florida Ave., where you can enjoy beers, socialize, and network with awesome local techies. Whether you're new to Microsoft 365 or an experienced M365 IT Pro / Developer, this event is a great opportunity to meet new faces and get to know your local counterparts.

**Comment by chtzvt** [comment]
Your group has been added to the feed ✨
